#! /usr/bin/awk -f
BEGIN {
    e    = ENVIRON["INSIDE_EMACS"];
    COLS = ENVIRON["TCOLS"] + 0;
}
{
    if (e && length($0) > COLS) {
        print substr($0, 1, COLS) " ...";
    } else {
        print;
    }
}
